name: Unet2D
description: A 2d U-Net pretrained on broad nucleus dataset.
cite: "Ronneberger, Olaf et al. U-net: Convolutional networks for biomedical image segmentation. MICCAI 2015."
version: 0.0.1
docs: README.md

requirements:
  conda:
    - python=3.6.8
    - pytorch=1.1.0
  pip:
    - pyyaml

entrypoint: __main__.py

config:
  model:
    definition:
      hash: 12
      name: model.UNet2d
      kwargs: { input_channels: 1, output_channels: 1 }
    weights:
      source: 10.5281/zenodo.3446812
      hash: { md5: c16cb3ba3cb9d257550fd19067ecfb91 }
    documentation: unet2d.md
    input_axes: "cyx"
    input_size: [1, 256, 256]
    minimal_valid_step: [0, 32, 32]
    output_axes: "cyx"

  training:
    loss:
      name: BCELoss
      kwargs: { reduction: "mean" }
      transformations:
        - { name: Sigmoid }
    optimizer:
      name: Adam
      kwargs: { lr: 0.002 }
    pretrained_on:
      datasets:
        - { name: NucleiDataset } # optional: source : {identifier: doi/url, hash: hash_value}
      n_iterations: 500
    batch_size: 4

  data:
    input_transformations:
      - { name: NormalizeZeroMeanUnitVariance, kwargs: { eps: 0.000001 } }
    output_transformations:
      - { name: Sigmoid }
